---
title: "lab 9 part 2"
author: "Max Settineri"
date: "2023-03-15"
output: html_document
---

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
```

## Useful functions in `stringr`

### Detect a pattern with `stringr::str_detect()`

```{r}
### make a practice vector
vec <- c('   A Unicorn    Fish',
         ' add   cornmeal ',
         '     French FRIES',
         '    acorn squash123    ')

### try detecting some patters
str_detect(vec, pattern = 'corn')
str_detect(vec, pattern = 'fish')
str_to_lower(vec) %>% str_detect(pattern = 'fish')

### let's extract some strings
str_extract(vec, pattern = 'corn')
str_extract(vec, pattern = '[a-z]')
str_extract(vec, pattern = '[0-9]') %>% as.numeric()
str_extract(vec, pattern = '[a-z]+')
str_extract_all(vec, pattern = '[a-z]+')
```

```{r}
walk_subset <- starwars %>% 
  filter(str_detect(name, pattern = 'walk'))

str_replace(vec, pattern = 'corn', replacement = 'COOL')
str_replace_all(vec, pattern = 'a', replacement = 'ZZZ')

sw_tornado <- starwars %>% 
  mutate(name = str_replace(name, pattern = 'Sky', replacement = 'TORNADO'))

sw_wacky <- starwars %>% 
  mutate(name2 = str_replace(name, pattern = '(w|W)b?a.+', replacement = 'WACKY')) %>% 
  select(name, name2)
```

```{r}
## trim extra white space
str_trim(vec) 
str_squish(vec) # removes interior space

## normally use these within mutate
```

### Let's use these in combination

```{r}
sw_combo <- starwars %>% 
  filter(str_detect(name, 'Darth')) %>% 
  mutate(name = str_replace(name, pattern = 'Darth', replacement = 'Llama')) %>% 
  mutate(name = str_to_lower(name))
```

